### ISSUE TITLE
Hydrawise Binary Sensor Issue

### ISSUE THREAD

**Issue by txwindsurfer** [ptcryan/hydrawiser#12]
This issue was reported in Home Assistant as #77087 back in August and remains open.  About 3 days ago after years of using the integration without any problems, I started getting this error after a reboot as well some other folks.
  
The error being reported and keeping the integration for loading is:

Error while setting up hydrawise platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/hydrawise/binary_sensor.py", line 64, in setup_platform
HydrawiseBinarySensor(hydrawise.current_controller, BINARY_SENSOR_STATUS)
File "/usr/src/homeassistant/homeassistant/components/hydrawise/init.py", line 96, in init
self._attr_name = f"{self.data['name']} {description.name}"
TypeError: list indices must be integers or slices, not str

I am running
Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

It could be intermittent as the integration loaded yesterday but today after a reboot will not load with this error.  It does not appear to be a rate limiting issue as an http call to the api using my key (https://api.hydrawise.com/api/v1/statusschedule.php?api_key=   ) returns the correct status of my Hydrawise system.  

Thank you for this integration.  It is extremely useful for automating my 19 irrigation zones. Please let me know how I can help.

**Comment by N3rdix** [comment]
Would be interesting what https://app.hydrawise.com/api/v1/customerdetails.php?api_key=TOKEN returns for the affected users. I am using an HC 601 and do not have an issue so far...

**Comment by robertboccia** [comment]
have same issue, any response on resolution?

**Comment by N3rdix** [comment]
> have same issue, any response on resolution?

Could you share what the API I mentioned above returns in your case?

**Comment by robertboccia** [comment]
> > have same issue, any response on resolution?
> 
> Could you share what the API I mentioned above returns in your case?

https://github.com/home-assistant/core/issues/83540

**Comment by N3rdix** [comment]
> > > have same issue, any response on resolution?
> 
> > 
> 
> > Could you share what the API I mentioned above returns in your case?
> 
> 
> 
> https://github.com/home-assistant/core/issues/83540

I meant the Hydrawise API endpoint, the error in Home Assistant is clear. Just paste your token from the configuration at the end of the URL I mentioned in the earlier post https://github.com/ptcryan/hydrawiser/issues/12#issuecomment-1346059312

**Comment by robertboccia** [comment]
Do you work for hydrawise?

**Comment by N3rdix** [comment]
No, and I don't get the point on that question... Just willing to help and started analyzing the issue on my DEV instance without such an error.

BTW, you should edit your previous message, seems like you forwarded your whole email ;-)

**Comment by txwindsurfer** [comment]
> Would be interesting what https://app.hydrawise.com/api/v1/customerdetails.php?api_key=TOKEN returns for the affected users. I am using an HC 601 and do not have an issue so far...

I currently get a status: All Good!  and my integration is currently connected to the api.  However, my experience is that if I reboot HA about 75% of the time there will be a failure of the integration to connect to the api and the binary_sensor error is reported.

**Comment by assafms** [comment]
I am not sure this is connected , but Hydrawise has added a limit to the amount of calls to the endpoints. if you call some of them more than 5 times in 5 minutes you get this :
"Exceeded maximum number of requests. You cannot make more than 5 requests in any 5 minute period to this endpoint."

when I remove the integration , wait for 5 min and then add it again (with the same API key) everything works again until the next time I restart .

**Comment by N3rdix** [comment]
I just created a PR #13 which at least forwards the exception to the consumer (Home Assistant integration). This would currently lead to a persistent notification in HA, which at least makes the issue visible to the user.

I'm wondering if the rate limit in general will conflict with the default scan interval of 30 seconds...

Maybe @ptcryan can decide if this PR is helpful and create a PyPi version at the end...

**Comment by txwindsurfer** [comment]
The hydrawise integration loads and runs using the code in the PR created by @N3rdix even if you have previously exceeded the maximum api calls. You will see an error in your logs if too many requests to the hydrawise endpoint are made (5 times in 5 minutes limit) and the service request causing the error will not execute.  After sufficient time has passed, service requests will once again start executing. Setting scan_interval: 120 in configuration helps to eliminate or reduce the errors, but basically, you can't call the hydrawise service more than 5 time in 5 minutes or your service request will fail with an error in the logs.

**Comment by N3rdix** [comment]
Although the error is now visible I assume there still needs some work to be done on the integration itself.

With the latest rate limit introduced by Hydrawise it would make sense to have a configurable scan interval.

Another idea which might help: make the integration async like others do, but I am not an expert on that
