### ISSUE TITLE
Hydrawise API Pdf

### ISSUE THREAD

**Issue by Bigben83** [ptcryan/hydrawiser#4]
the link you provided for the Hydrawise API is no longer active. would you be able to send me a copy ?
https://support.hydrawise.com/hc/en-us/article_attachments/205632298/Hydrawise_API.pdf

**Comment by ptcryan** [comment]
Hi Bigben83. I put the pdf in issue #5 

https://github.com/ptcryan/hydrawiser/issues/5#issuecomment-589456821
